name: "HCL AppScan CodeSweep"
on:
  pull_request:
    types: [opened,synchronize]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: ${{8b8c367b-fbd0-9909-4aff-60af56e3a21e}}
          asoc_secret: ${{kiXAlXEtwLGEgPNIOMT8jqR5ACriE9eCmwNqAwkySlA=}}
    env: 
      GITHUB_TOKEN: ${{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}}
