name: "HCL AppScan CodeSweep"
on:
  pull_request:
    types: [master]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish issues to ASoC
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          publish_on_merge: true
          application_id: b29462b1-810c-4e83-afcb-18dd6b5bc327
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
